### ISSUE TITLE
Python or any non-matlab code for Pano2Photo

### ISSUE THREAD

**Issue by ghost** [ariseff/mapnet#2]
First, thanks a lot for releasing the dataset of pano images from GSV. 
I am currently looking into reprojecting a crop just like pano2photo, however I dont want to use matlab in my pipeline. Is there any other equivalent code in OpenCV or ImageMagik  by any chance.
https://github.com/seffari/mapnet/tree/master/dependencies/pano2photo

**Comment by ariseff** [comment]
You're welcome! I hope the dataset proves useful for you. 

I haven't personally used a non-matlab alternative to pano2photo. However, I think the code may be relatively easy to reimplement in Python or another language of your choosing.

**Comment by ghost** [comment]
Thanks I will look into it.
